def module Proj4.TwitterClient do
    use GenServer
    @me __MODULE__

    def start_link(arg) do
        GenServer.start_link(@me, arg, name: @me)
    end

    def init(init_state) do
        {:ok, init_state}
    end

    def terminate(_reason, state) do
        IO.inspect state
        IO.puts "***** Exiting Twitter Client GenServer *****"
    end

    #All the requests are generated by the client

    def handle_cast({:recieve_tweet}) do
        # Here the user recieves the tweet from the server process and outputs it onto the screen
    end

    def handle_cast({:send_tweet}) do
        # Here the user sends a tweet request to the server process, server will store its tweet in its table
        # Then the server process will look for this user's subscriber's list; and send another request to all its subsribers to retweet {Those subsribers will actually recieve a tweet first}
    end

end